import { useEffect, useState, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { api } from "../api/client";
import { VoteButtons } from "../components/VoteButtons";
import { SECTIONS } from "../constants";

export function Dashboard() {
  const { token, user, logout } = useAuth();
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const result = await api.getDashboard(token);
      setData(result);
    } catch (err) {
      if (err.message === "Onboarding not completed") {
        navigate("/onboarding");
        return;
      }
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, [token, navigate]);

  useEffect(() => {
    load();
  }, [load]);

  async function handleVote(section, itemKey, vote) {
    try {
      await api.vote({ section, itemKey, vote }, token);
      setData((prev) => {
        if (!prev) return prev;
        const next = structuredClone(prev);
        const applyVote = (item) => {
          if (item.id === itemKey) item.userVote = item.userVote === vote ? null : vote;
        };
        if (Array.isArray(next.sections[section])) {
          next.sections[section].forEach(applyVote);
        } else {
          applyVote(next.sections[section]);
        }
        return next;
      });
    } catch (err) {
      setError(err.message);
    }
  }

  if (loading) return <div className="dashboard-page"><p>Loading your dashboard...</p></div>;
  if (error) return <div className="dashboard-page"><p className="error">{error}</p></div>;
  if (!data) return null;

  const { sections } = data;

  return (
    <div className="dashboard-page">
      <header className="dashboard-header">
        <div>
          <h1>Hi {user?.name} 👋</h1>
          <p className="subtitle">Your daily crypto briefing</p>
        </div>
        <div className="header-actions">
          <button className="secondary" onClick={load}>Refresh</button>
          <button className="secondary" onClick={logout}>Log out</button>
        </div>
      </header>

      <div className="dashboard-grid">
        <section className="card">
          <h2>📰 Market News</h2>
          <ul className="news-list">
            {sections.marketNews.map((item) => (
              <li key={item.id}>
                <a href={item.url} target="_blank" rel="noreferrer">{item.title}</a>
                <div className="item-footer">
                  <span className="muted">{item.source}</span>
                  <VoteButtons
                    userVote={item.userVote}
                    onVote={(vote) => handleVote(SECTIONS.MARKET_NEWS, item.id, vote)}
                  />
                </div>
              </li>
            ))}
          </ul>
        </section>

        <section className="card">
          <h2>💰 Coin Prices</h2>
          <ul className="price-list">
            {sections.coinPrices.map((coin) => (
              <li key={coin.id}>
                <div>
                  <strong>{coin.symbol}</strong>{" "}
                  <span>{coin.price != null ? `$${coin.price.toLocaleString()}` : "N/A"}</span>{" "}
                  {coin.change24h != null && (
                    <span className={coin.change24h >= 0 ? "positive" : "negative"}>
                      {coin.change24h >= 0 ? "▲" : "▼"} {Math.abs(coin.change24h).toFixed(2)}%
                    </span>
                  )}
                </div>
                <VoteButtons
                  userVote={coin.userVote}
                  onVote={(vote) => handleVote(SECTIONS.COIN_PRICES, coin.id, vote)}
                />
              </li>
            ))}
          </ul>
        </section>

        <section className="card">
          <h2>🤖 AI Insight of the Day</h2>
          <p className="insight-text">{sections.aiInsight.text}</p>
          <div className="item-footer">
            <span className="muted">
              {sections.aiInsight.source === "openrouter" ? "Generated by AI" : "Sample insight"}
            </span>
            <VoteButtons
              userVote={sections.aiInsight.userVote}
              onVote={(vote) => handleVote(SECTIONS.AI_INSIGHT, sections.aiInsight.id, vote)}
            />
          </div>
        </section>

        <section className="card">
          <h2>😂 Fun Crypto Memes</h2>
          {sections.meme.map((item) => (
            <div className="meme-item" key={item.id}>
              <img className="meme-image" src={item.url} alt={item.caption} />
              <div className="item-footer">
                <span className="muted">{item.caption}</span>
                <VoteButtons
                  userVote={item.userVote}
                  onVote={(vote) => handleVote(SECTIONS.MEME, item.id, vote)}
                />
              </div>
            </div>
          ))}
        </section>
      </div>
    </div>
  );
}
